language: python
python:
    - '2.7'
install:
    - pip install -r python/requirements/tests.txt --upgrade
    - sudo apt-get update && sudo apt-get install maven2 -y
script:
    - cd python && nosetests -s && cd ..
    - cd java && mvn clean test && cd ..
